#************************************************************
#
#	Instituto Tecnológico de Costa Rica
#	Ingeniería en Computadores
#
#	Programador: Esteban Agüero Pérez (estape11)
#
#	Última Modificación: 02/04/2019
#
#	Arquitectura de Computadores II
#	Prof. Jeferson González Gómez
#
#************************************************************

all: src

src:	
		$(MAKE) -C src

clean:
		$(MAKE) -C src clean
		clear

.PHONY:src